### ISSUE TITLE
Rubygem

### ISSUE THREAD

**Issue by stjhimy** [veeqo/mws-rb#16]
Is this maintained by Veeqo? https://rubygems.org/gems/mws-rb
I was wondering if we should release the latest version to Rubygems? 

Thanks

**Comment by DanielVartanov** [comment]
Yes, good point @stjhimy, we will do it, thanks for reminding.
We are using `git://` reference in our Gemfile, so we didn't bother releasing it to Rubygems

**Comment by DanielVartanov** [comment]
Oops, it looks like you own it on Rubygems, can you transfer ownership to `daniel_vartanov` on Rubygems please?

I'll automate gem releasing.

**Comment by stjhimy** [comment]
@DanielVartanov I'm the author not the owner, the owner is this profile: https://rubygems.org/profiles/automat
startupsignup%2Brubygems@gmail.com

Maybe someone published without owning the gem on github?

**Comment by DanielVartanov** [comment]
hum, I'll investigate it with Rubygems support, strange.

**Comment by DanielVartanov** [comment]
FYI: I contacted both current owner and rubygems support, awaiting for their answer.

**Comment by stjhimy** [comment]
is it also possible to set up a travis ci build for the project?

**Comment by DanielVartanov** [comment]
Yep, thanks for another great point, I will.

**Comment by DanielVartanov** [comment]
Done
https://travis-ci.org/veeqo/mws-rb

Sorry for a delay, thanks for preparing `.travis.yml` file!

**Comment by DanielVartanov** [comment]
Letting you know, still no answer concerning the gem. There is a chance we will need to pick a new gem name in order to distribute it over rubygems.org

**Comment by stjhimy** [comment]
This is sad. 
Maybe we could use `mws_rb` instead? It's available on rubygems https://rubygems.org/search?utf8=%E2%9C%93&query=mws_rb

**Comment by DanielVartanov** [comment]
Hey Jhimy,
Sorry for delay. Agreed, let's do `mws_rb`.
I am going to do

`gem 'mws_rb', require: 'mws'`

Sounds good?

**Comment by stjhimy** [comment]
Yes.

Will you update the code or should I? 
Thanks!

**Comment by DanielVartanov** [comment]
I'll do it today.

**Comment by DanielVartanov** [comment]
Done!
You can `gem install mws_rb` now. Please let me know if there is a problem
